### ISSUE TITLE
Build failing on Ubuntu 12.04

### ISSUE THREAD

**Issue by iiSeymour** [ryancole/hdf5.node#2]
I'm trying to build on Ubuntu Linux 12.04 which fails with the following:

```bash
$ node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.1
gyp info using node@0.10.26 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cseymour/Code/node/node5/hdf5.node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/csyemour/.node-gyp/0.10.26/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/cseymour/.node-gyp/0.10.26',
gyp info spawn args   '-Dmodule_root_dir=/home/cseymour/Code/node/node5/hdf5.node',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/cseymour/Code/node/node5/hdf5.node/build'
  CXX(target) Release/obj.target/h5im/src/h5im.o
In file included from ../src/h5im.cc:2:0:
../src/hdf5.h:20:66: error: a brace-enclosed initializer is not allowed here before ‘{’ token
In file included from ../src/h5im.cc:2:0:
../src/hdf5.h:20:178: error: ISO C++ forbids initialisation of member ‘toAccessMap’ [-fpermissive]
../src/hdf5.h:20:178: error: making ‘toAccessMap’ static [-fpermissive]
../src/hdf5.h:20:178: error: invalid in-class initialisation of static data member of non-integral type ‘std::map<long unsigned int, long unsigned int>’
../src/hdf5.h:34:36: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:34:40: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:34:60: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:35:44: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:35:48: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:35:68: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:36:42: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:36:46: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:36:66: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:45:13: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
../src/hdf5.h:47:36: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:47:40: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:47:60: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:54:39: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:54:43: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:54:63: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:55:37: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:55:41: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:55:61: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:56:44: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:56:48: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:56:68: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:57:50: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:57:54: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:57:74: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:58:46: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:58:50: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:58:70: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:59:43: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:59:47: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:59:67: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:60:47: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:60:51: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:60:71: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/hdf5.h:61:62: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/hdf5.h:61:66: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/hdf5.h:61:86: error: expected ‘,’ or ‘...’ before ‘<’ token
In file included from ../src/h5im.cc:3:0:
../src/h5_im.hpp:25:31: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/h5_im.hpp:25:35: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/h5_im.hpp:25:55: error: expected ‘,’ or ‘...’ before ‘<’ token
In file included from ../src/h5im.cc:3:0:
../src/h5_im.hpp:40:31: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/h5_im.hpp:40:35: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/h5_im.hpp:40:55: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/h5_im.hpp:67:29: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../src/h5_im.hpp:67:33: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/h5_im.hpp:67:53: error: expected ‘,’ or ‘...’ before ‘<’ token
In file included from ../src/h5im.cc:3:0:
../src/h5_im.hpp: In static member function ‘static void NodeHDF5::H5im::Initialize(v8::Handle<v8::Object>)’:
../src/h5_im.hpp:19:21: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
In file included from ../src/h5im.cc:3:0:
../src/h5_im.hpp:19:147: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Isolate*, void (&)(int))’
../src/h5_im.hpp:19:147: note: candidate is:
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:2255:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::InvocationCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>)
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:2255:34: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
../src/h5_im.hpp:20:21: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:20:147: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Isolate*, void (&)(int))’
../src/h5_im.hpp:20:147: note: candidate is:
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:2255:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::InvocationCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>)
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:2255:34: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
../src/h5_im.hpp:21:21: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:21:143: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Isolate*, void (&)(int))’
../src/h5_im.hpp:21:143: note: candidate is:
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:2255:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::InvocationCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>)
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:2255:34: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
../src/h5_im.hpp: In static member function ‘static void NodeHDF5::H5im::make_image(int)’:
../src/h5_im.hpp:28:34: error: ‘args’ was not declared in this scope
../src/h5_im.hpp:29:11: error: ‘Uint8Array’ was not declared in this scope
../src/h5_im.hpp:29:21: error: template argument 1 is invalid
../src/h5_im.hpp:29:30: error: invalid type in declaration before ‘=’ token
../src/h5_im.hpp:29:49: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> class v8::Local’
../src/h5_im.hpp:29:49: error:   expected a type, got ‘Uint8Array’
../src/h5_im.hpp:32:40: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:32:46: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:33:14: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:33:20: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:35:90: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:35:96: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:35:180: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:35:186: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
In file included from ../src/h5im.cc:3:0:
../src/h5_im.hpp:35:306: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:35:16: warning: unused variable ‘err’ [-Wunused-variable]
../src/h5_im.hpp: In static member function ‘static void NodeHDF5::H5im::read_image(int)’:
../src/h5_im.hpp:43:34: error: ‘args’ was not declared in this scope
../src/h5_im.hpp:51:5: error: ‘unique_ptr’ is not a member of ‘std’
../src/h5_im.hpp:51:21: error: expected primary-expression before ‘unsigned’
../src/h5_im.hpp:51:21: error: expected ‘;’ before ‘unsigned’
../src/h5_im.hpp:52:11: error: ‘Uint8Array’ was not declared in this scope
../src/h5_im.hpp:52:21: error: template argument 1 is invalid
../src/h5_im.hpp:52:30: error: invalid type in declaration before ‘=’ token
../src/h5_im.hpp:52:32: error: ‘Uint8Array’ is not a class or namespace
../src/h5_im.hpp:52:48: error: ‘ArrayBuffer’ has not been declared
../src/h5_im.hpp:53:66: error: ‘contentBuffer’ was not declared in this scope
../src/h5_im.hpp:56:15: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:58:11: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:58:17: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:58:118: error: no matching function for call to ‘v8::Number::New(v8::Isolate*, hsize_t&)’
../src/h5_im.hpp:58:118: note: candidate is:
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:1377:33: note: static v8::Local<v8::Number> v8::Number::New(double)
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:1377:33: note:   candidate expects 1 argument, 2 provided
../src/h5_im.hpp:59:11: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:59:17: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:59:120: error: no matching function for call to ‘v8::Number::New(v8::Isolate*, hsize_t&)’
../src/h5_im.hpp:59:120: note: candidate is:
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:1377:33: note: static v8::Local<v8::Number> v8::Number::New(double)
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:1377:33: note:   candidate expects 1 argument, 2 provided
../src/h5_im.hpp:60:11: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:60:17: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:60:120: error: no matching function for call to ‘v8::Number::New(v8::Isolate*, hsize_t&)’
../src/h5_im.hpp:60:120: note: candidate is:
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:1377:33: note: static v8::Local<v8::Number> v8::Number::New(double)
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:1377:33: note:   candidate expects 1 argument, 2 provided
../src/h5_im.hpp:61:11: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:61:17: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:61:78: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:62:11: error: base operand of ‘->’ is not a pointer
../src/h5_im.hpp:62:17: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/h5_im.hpp:62:118: error: no matching function for call to ‘v8::Number::New(v8::Isolate*, hssize_t&)’
../src/h5_im.hpp:62:118: note: candidate is:
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:1377:33: note: static v8::Local<v8::Number> v8::Number::New(double)
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:1377:33: note:   candidate expects 1 argument, 2 provided
../src/h5_im.hpp: In static member function ‘static void NodeHDF5::H5im::is_image(int)’:
../src/h5_im.hpp:70:34: error: ‘args’ was not declared in this scope
../src/h5im.cc: In function ‘void init_im(v8::Handle<v8::Object>)’:
../src/h5im.cc:13:52: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*)’
../src/h5im.cc:13:52: note: candidates are:
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/home/cseymour/.node-gyp/0.10.26/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
make: *** [Release/obj.target/h5im/src/h5im.o] Error 1
make: Leaving directory `/home/cseymour/Code/node/node5/hdf5.node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.2.0-58-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/cseymour/Code/node/node5/hdf5.node
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
```

With `V8` version:

``` bash
$ node -e "console.log(process.versions.v8)"
3.14.5.9
```

Any ideas?

**Comment by rimmartin** [comment]
http://nodejs.org/ v0.12.0 is out!

testing with it and the harmony switch
